# -*- mode: org; coding: utf-8 -*-
#+STARTUP: overview
* -----------------------------------------------------------------------------------------------
** Term
#  :drill:
  :PROPERTIES:
  :END:
Something [like] this
* Finance
** Term 							      :drill:
  :PROPERTIES:
  :END:
[silent seconds]: is a second mortgage placed on an asset for down payment funds
that are not disclosed to the oriignal lender on the first mortgage.
** Term 							      :drill:
  :PROPERTIES:
  :END:
[sell-side]: the part of the financial industry that is involved in the
creation, promotion, and sale of stocks, bonds, foreign exachange, and other
fincial instruments.
** Term 							      :drill:
  :PROPERTIES:
  :END:
[security]: a tradable financial assett. Commonly refers to any form of
financial instrument.
** Term 							      :drill:
  :PROPERTIES:
  :END:
[credit default swap] (CDS): [financial swap] agreement that the seller of the
CDS will compensate the buyer in the event of a debt default or other credit
event. The seller of the CDS insuresthe buyer against some reference asset
defaulting.
** Term 							      :drill:
  :PROPERTIES:
  :END:
[collateralized debt obiligations]: CDO, add more
** Term 							      :drill:
  :PROPERTIES:
  :END:
[synthetic collateralized debt obligation]: (CDO) while a traditional CDO
generates income for the seller from cash assets like loans, credit cards,
mortages, the value of a [synthetic CDO] comes from insurance premiums of
credit default swaps paid for by investors. The seller takes a long position,
while the buyer takes a short position.
