# Quotes

* Best
"The one unforgivable sin is to be boring."
   - Christopher Hitchens quoting his mother

"All could see her face was as pretty as a flower, but none could know that in
 her fair and gracious breast there raged a desire to hunt down her enemies.

 People say you can’t wash away the mud of this world with pure white snow:

 You need asura snow, stained fiery red."
   - Lady Snowblood

"What you are shouts so loudly in my ears I cannot hear what you say."
   - Ralph Waldo Emerson



* Art
"Irony is to art what kryptonite is to Superman. Irony kills art. Nothing can be
 moving, meaningful, joy inducing or tear-wrenching if irony is involved,
 because anything that is ironic positions itself as superior to standard human
 emotion, superior to anything that can touch you."
   - [[https://www.insidehook.com/article/music/weezers-africa-worst-pop-recording-time][Why Weezer’s “Africa” Is the Worst Pop Recording of All Time]]

"I don’t design clothes for the Queen; but for the people who wave at her as
 she goes by."
   - Willi Smith


* Death
"Another repied to his confessor, who was promising him that he should sup that
 day with Our Lord: You go there yourself; for my part, I'm fasting."
   - Michel de Montaigne, That the Taste of Good and Evil Depends in Large Part
                         on the Opinion We Have of Them

"Nature’s a lot brighter than what people think. Little by little, we lose our
 friends that we care about, and little by little, we lose our interests til’
 finally we say 'well what the hell am I doing around here', we have no reason
 to go on. But I have a reason with Mike here."
   - Cus D'Amato speaks about old age and his reason to stay alive.

"Death holds less pain than does the wait for death"
   - Ovid

"Is there any meaning in my life that the inevitable death awaiting me does not
 destroy"
   - Leo Tolstoy

Memento Mori: Latin for 'remember that you must die'

"I have lived longer by this one day than I should have done."
   - Macrobius


* Finance
"“the extension of credit by instrument.” That is, a lot of people couldn’t
 actually afford to pay their mortgages the old-fashioned way, and so the
 lenders were dreaming up new financial instruments to justify handing them new
 money."
   - Michael Lewis on Michael Burry's original quote

"If you're reading about it in the paper, it's too late."
   - from The Big Short


* Freedom
"A pawn acts like a pawn because it believes its a pawn"
   - An Old Man playing chess, Wu-Tang: An American Saga

"If one minute’s freedom had been offered to me, and I had been told must die at
 the end of that minute, I would have taken it."
   - Mum Bett

"There are only three real sports: bullfighting, mountain climbing, and motor
racing. The rest are merely games."
   - Ernest Hemingway



* Happiness
"Some people are so much sunshine to the square inch."
   - Walt Whitman

"Happy the man, and happy he alone,
 He who can call today his own;
 He who, secure within, can say,
 Tomorrow do thy worst, for I have lived today."
   - Translation of Horace by John Dryden

"For people are happy not in hilarity or sensuality or laughter, nor in games,
 the comrades of levity, but often even in sadness through firmness and
 constancy"
   - Cicero

"Happiness is reality minus expectations"

"It’s easier to desire and pursue the attention of tens of millions of total
 strangers than it is to accept the love and loyalty of the people closest to
 us."
   - William Gibson, Idoru


* Humor
"In the beginning the Universe was created. This has made a lot of people very
 angry and has been widely regarded as a bad move."
   - Douglas Adams

"Why don't you take your library card and fuck off."
   - Logan Roy, Succession 2:4

"How does working on this case effect your sex life?"
"Mine? Doesn't effect mine, it effects yours, go fuck yourself."
   - Manhunter, 49:45

"Find the quote about the American insulting the King, and the Englishman
 insulting Babe Ruth"
   - PBS, Ken Burn's Baseball, episod IV, 10ish minutes in?

"Even on the highest throne in the world, we are still sitting on our ass."
   - Michel de Montaigne

"But there was always a moldy thrift store stink of irony about Weezer;"

"On the planet emacs in the holy control tower" - spacemacs

"Difficulty is a coin which the learned conjure with so as not to reveal the
 vanity of their studies and which human stupidity is keen to accept as payment"
   - Michel de Montaigne

"But with the invention of the modern prison system, everything happened in
 private, behind locked gates. One could no longer see and therefore resist
 state power."
   - Based on Foucault's Discipline and Punish

"The most difficult thing in the world is to know how to do a thing and to watch
 someone else do it wrong without comment."
   - Theodore H. White


* Labour
"Christopher Hitchens defined happiness as solitary work during the day, in
 anticipation of company that evening."
   - Janen Ganesh, [[https://www.ft.com/content/311b9b4e-6456-11ea-a6cd-df28cc3c6a68][ft]]

:Fashionable-Problems:
"I've seen a similar pattern in many different fields: even though lots of
 people have worked hard in the field, only a small fraction of the space of
 possibilities has been explored, because they've all worked on similar things.

 Even the smartest, most imaginative people are surprisingly conservative when
 deciding what to work on. People who would never dream of being fashionable in
 any other way get sucked into working on fashionable problems.

 If you want to try working on unfashionable problems, one of the best places to
 look is fields that people think have already been fully explored: essays,
 Lisp, venture funding – you may notice a pattern here. If you can find a new
 approach into a big but apparently played out field, the value of whatever you
 discover will be multiplied by its enormous surface area.

 The best protection against getting drawn into working on the same things as
 everyone else may be to genuinely love what you're doing. Then you'll continue
 to work on it even if you make the same mistake as other people and think that
 it's too marginal to matter."
   - [[http://paulgraham.com/fp.html][Paul Graham]]
:end:

"All professions are conspiracies against the laity."
   - George Bernard Shaw


* Life
"Tuesday: nothing. existed."
   - Jean-Paul Sartre, Nausea

"Death destroys a man; the idea of Death saves him"
   - E. M. Forster

"He came home weighing ninety-eight pounds. 'My wife cooks good food for me,'
 Muongkhot said. 'Today, I’m at a hundred and five.
 Two numbers. Now I got three.'"
   - Lauren Hilgers,
     [[https://www.newyorker.com/magazine/dispatch/how-two-waves-of-coronavirus-cases-swept-through-the-texas-panhandle][How Two Waves of Coronavirus Cases Swept Through the Texas Panhandle]]

"A friend is, as it were, a second self."
   - Marcus Tullius Cicero

"Not being able to govern events, I govern myself"
   - Montaigne

"If you want to make progress, put up with being perceived as ignorant or naive
 in worldly matters, don't aspire to a reputation for sagacity. If you do
 impress others as somebody, don't altogether believe it. You have to realize,
 it isn't easy to keep your will in agreement with nature, as well as externals.
 Caring about the one inevitably means you are going to shortchange the other"
   - Epictetus

"Let everything happen to you
      Beauty and terror
       Just keep going
     No feeling is final."
   - Rainer Maria Rilke

"I laugh so I do not cry"

"Don’t you ever let a soul in the world tell you that you can’t be exactly who
 you are."
   - Lady Gaga, [[https://www.nytimes.com/2020/02/27/opinion/lady-gaga-boyfriend.html][from here]]

"The devil may care, but I do not."

"If you only read the books that everyone else is reading, you can only think
 what everyone else is thinking."
   - Haruki Murakami, Norwegian Wood

"The best bridge between despair and hope is a good night’s sleep"
   - E. Joseph Cossman, American entrepreneur

"You could leave life right now. Let that determine what you do and say and
 think."
   - Marcus Aurelius, Meditations

"All gas no brakes"

"I think we get it wrong a lot, especially in this country. It's all about
 winning. Winning, winning, winning. People who are considered "winners" are in
 my mind, some of the great losers of all time and people who are considered
 "losers" are, to me, some of the great winners of all time."
   - Ron Shelton

"Sometimes you have to play a long time to be able to play like yourself."
   - Miles Davis

"It is said that his time was easier than ours, but I doubt it — no time can be
 easy for one who is living through it."
   - James Baldwin on Shakespeare

"What cannot be cured, must be endured"

"... we actually have no choice but to fall in love, as biology is stronger than
 reason"
   - Arthur Schopenhauer

"Above all, don't lie to yourself. The man who lies to himself and listens to
 his own lie comes to a point that he cannot distinguish the truth within him,
 or around him, and so loses all respect for himself and for others. And having
 no respect he ceases to love… Above all, avoid falsehood, every kind of
 falsehood, especially to yourself."
   - Zosima, The Brothers Karamozov

"the most reasonable and widely accepted definition of personality is behaviour
 of an individual which is relatively constant over time and doesn’t depend on
 context (Perugni et al, 2016)"
   - [[https://medium.com/@Soccermatics/how-swedes-were-fooled-by-one-of-the-biggest-scientific-bluffs-of-our-time-de47c82601ad][How Swedes Were Fooled]]

"Life is at your hands, not others. Everyone needs to strive and struggle on his
 or her own. A better world can be made and they are making it happen. That's
 the faith of the people living in the cave houses on the Loess Plateau."
   - Lu Yao, World of Plainness



* Literature
“Lina’s hair is down and her dark eyes, fresh from church, have a familiarly
 Italian mournful expression.”
   - Philip Roth Portnoy’s Complaint


* Love
"It doesn't matter how I see you, just so I see you."
   - Kay Lawrence, I Walk Alone


* Motivation
:Ire-Glass:
"Nobody tells this to people who are beginners, I wish someone told me. All of
 us who do creative work, we get into it because we have good taste. But there
 is this gap. For the first couple years you make stuff, it’s just not that
 good. It’s trying to be good, it has potential, but it’s not. But your taste,
 the thing that got you into the game, is still killer. And your taste is why
 your work disappoints you.

 A lot of people never get past this phase, they quit. Most people I know who do
 interesting, creative work went through years of this. We know our work doesn’t
 have this special thing that we want it to have. We all go through this. And if
 you are just starting out or you are still in this phase, you gotta know its
 normal and the most important thing you can do is do a lot of work.

 Put yourself on a deadline so that every week you will finish one story. It is
 only by going through a volume of work that you will close that gap, and your
 work will be as good as your ambitions. And I took longer to figure out how to
 do this than anyone I’ve ever met. It’s gonna take awhile. It’s normal to take
 awhile. You’ve just gotta fight your way through."
:end:

"No matter what anyone says, no matter the excuse or explanation, whatever a
 person does in the end is what he intended to do all along."
   - Cus D'Amato

"If you want nothing, do what you want. If you want everything, develop
 discipline."
   - Kostya Tszyu

"Life begins at 55, the age at which I published my first book"
   - Dr. Freeman Dyson, From Eros to Gaia

"When you feel guilty, but haven’t harmed anyone, then you’re just in the realm
 of perfectionism or criticism"
   - Dr. Neff

"Your rest is just as important as your work"
   - through T. to Me

"The easiest way to be discovered right now in technology and perhaps many
 fields is to create your own independent blog and write. There is a huge dearth
 in availability of good, current, first party content today.

 The single most important advice I can give to actually write is to write.

 The thing that happens which you don’t see until you write is that your content
 engages some of the smartest people who are lurking around the internet. And
 they reach out to you."
   - Steve Cheney

"You don't rise to your goals, you fall to the level of your systems"
   - James Clear

"Most geniuses—especially those who lead others—prosper not by deconstructing
 intricate complexities but by exploiting unrecognized simplicities."
   - Andy Benoit

"Impress the crowd when you are alone, impress yourself when you are in a
 crowd."
   - T.

"When I feel panic-stricken about a task, I repeat a mantra I read in Haruki
 Murukami’s memoir, What I Talk About When I Talk About Running, which the
 author uses when he feels he cannot run any further: ‘I’m not human. I’m a
 piece of machinery . . . Just forge on ahead’."
   - [[https://www.ft.com/content/9cf6a48e-395a-11ea-ac3c-f68c10993b04][Carl Cederstrom]]

"At critical moments in time, you can raise the aspirations of other people
 significantly, especially when they are relatively young, simply by suggesting
 they do something better or more ambitious than what they might have in mind.
 It costs you relatively little to do this, but the benefit to them, and to the
 broader world, may be enormous. This is in fact one of the most valuable things
 you can do with your time and with your life."
   - Tyler Cowen:



* On Drink
"Once, on a trek through Afghanistan, we lost our corkscrew ... and were
 compelled to live on food and water for several days."
   - W.C. Fields, My Little Chickadee

"I was in love with a beautiful blonde once, dear. She drove me to drink. That's
 the one thing I am indebted to her for."
   - W.C. Fields, Never Give a Sucker an Even Break


* Politics
“Your representative owes you, not his industry only, but his judgment; and he
 betrays, instead of serving you, if he sacrifices it to your opinion.”
   - Edmund Burke

“The majority is always wrong. The minority is rarely right.”
   - Henrik Ibsen

"Nothing on the St. Anthony’s block is a remedy for homelessness, but the
 harmony shows that it is possible to create shared space and resources on a
 small scale—also known as a community."
   - [[https://www.newyorker.com/magazine/2020/06/01/a-window-onto-an-american-nightmare][A Window Onto an American Nightmare]]

“If everybody is thinking alike, then no one is thinking.”
   - Benjamin Franklin

"Intellectually deprived Americans had thrilled to Buckley’s overwrought and
 often pretentious manner, his cute logic-chopping and word play, but this cut
 less ice in Cambridge."
   - The Fire is Upon Us [[https://www.the-tls.co.uk/articles/fire-is-upon-us-by-nicholas-buccola-book-review/][book review]]

"And so for many Americans, the nuclear family has become a lonely institution -
 and childhood, one long unpaid internship meant to secure a spot in a dwindling
 middle class"
   - Kim Brooks, NYT

"In politics, identity is an appeal to authority — the moral authority of the
oppressed: I am what I am, which explains my view and makes it the truth. The
politics of identity starts out with the universal principles of equality,
dignity, and freedom, but in practice it becomes an end in itself — often a dead
end, a trap from which there’s no easy escape and maybe no desire for escape"
   - George Packer, [[https://www.theatlantic.com/magazine/archive/2019/10/when-the-culture-war-comes-for-the-kids/596668/][When the Culture War Comes for the Kids]]

“Men are afraid that women will laugh at them. Women are afraid that men will
 kill them.”
   - Margaret Atwood

“Progress is never permanent, will always be threatened, must be redoubled,
 restated and reimagined if it is to survive.”
   - Zadie Smith



* Programming
“The problem of object-oriented languages is they’ve got all this implicit
 environment that they carry around with them. You wanted a banana but what you
 got was a gorilla holding the banana and the entire jungle.”
   - Joe Armstrong

"GPLv3: as worthy a successor as The Phantom Menace, as timely as Duke Nukem
 Forever, and as welcome as New Coke."
   - Rob Landley, [[http://lists.busybox.net/pipermail/busybox/2010-December/074114.html][Understanding the bin, sbin, usr/bin, usr/sbin split]]


* Race
"We are not pressing toward the brink of violence, but for the peak of freedom"
   - James Farmer


* Racing
*** Stirling Moss
Motion, he said, was tranquillity. Why, he wondered, do people walk, since God
gave them feet that fit automotive pedals?

Moss, the ultimate pro, once observed that there are no professionals at dying
 — although he had practiced. He was sure he was "a goner" after his steering
column snapped at over 160 m.p.h. in a race in Monza, Italy, in 1958. As he
staggered away from the wreckage, he thought, "Well, if this is hell, it’s not
very hot, or if it’s heaven, why is it so dusty?"

"Who do you think you are, Stirling Moss?" Moss, who had been knighted, was once
 asked that question, and answered, "Sir Stirling, please."


* Religion
He "regarded all religions with the suspicion of a seasoned con man"
   - James Curis on W. C. Fields was an atheist


* Science
"Existing order that is kept up."
   - Antonio Damasio, The Strange Order of Things

"I think it’s almost true without exception if you want to win a Nobel Prize,
 you should have a long attention span, get hold of some deep and important
 problem and stay with it for 10 years, that wasn’t my style."
   - Dr. Freeman Dyson

"Why are you keeping this curiosity door locked?"
   - Dustin, Stranger Things


* Stories
:Chinese-chilie-farmer:
Late one night last week, the village committee put out a call on the messaging
app WeChat, asking local farmers for extra produce that they could send to
Wuhan. Mr. Li swung into action.

He, his wife and their two daughters grabbed flashlights and worked through the
night. They harvested half a ton of chilies, twice their normal daily output.

Mr. Li said he had not yet heard from the authorities about when or what he
might be paid for his contribution. If it ends up being a gift, that would be
all right by him, he said. When Shouguang suffered catastrophic flooding in
recent years, people from across China came to his and other farmers’ aid.

“We cannot forget that,”
   - [[https://www.nytimes.com/2020/02/04/business/china-coronavirus-food-prices.html?action=click&module=Top%2520Stories&pgtype=Homepage][Mr. Li]]
:end:
:typhoid-doctor:
"The wider world is mostly characterized by wicked learning environments, where
 you can’t see information. It’s hidden from us. Feedback is delayed and
 sometimes inaccurate.

 One of the examples is a famous New York City physician who was renowned for
 his ability to predict that patients would get typhoid. He predicted the
 sickness time and again. He would palpate their tounge (feel around their
 tongue) and predict, weeks before patients had a single symptom, over and over,
 and became famous, and as one of his colleagues said, he was a more productive
 carrier of typhoid than even Typhoid Mary because he was giving his patients
 Typhoid with his hands. In that case, the feedback he was receiving was
 reinforcing exactly the wrong lesson.

 So that’s the extreme of a wicked environment where your feedback teaches
 exactly the wrong lesson."
   - David Epstein
:end:


* Thoughts
“The mind of man, which he did not ask to be given, demands a reason”
   - Intro to Nausea

"And if I am a man of some reading, I am a man of no retentiveness"
   - Michel de Montaigne

"Chess problems demand from the composer the same virtues that characterize all
 worthwhile art: originality, invention, conciseness, harmony, complexity, and
 splendid insincerity."
   - Vladimir Nabokov, Poems and Problems

"Hypocrisy is the homage vice pays to virtue."

"Get rid of your lawns, lawns are total biological deserts. It’s just grass with
 pesticides. The way it’s grown does not support a lot of biodiversity."
   - Dr. May Berenbaum

"Better three hours too soon than a minute too late."
   - Shakespeare

"The forest was shrinking, but the Trees kept voting for the Axe, for the Axe
 was clever and convinced the Trees that because his handle was made of wood, he
 was one of them."
   - Proverb

"So marvelous is the power of conscience! It makes us betray, accuse and fight
 ourselves, and, in the absence of an outside witness, it brings us forward
 against ourselves."
       `Plying a secret whip, our soul as torturer.` - Juvenal
   - Michel de Montaigne

"Spirit of iron makes skin of stone."
   - Ta-Nehisi Coates, Black Panther

“I used to have students who bragged to me about how fast they wrote their
 papers. I would tell them that the great German novelist Thomas Mann said that
 a writer is someone for whom writing is more difficult than it is for other
 people. The best writers write much more slowly than everyone else, and the
 better they are, the slower they write. James Joyce wrote Ulysses, the
 greatest novel of the 20th century, at the rate of about a hundred words a
 day.”
   - William Deresiewicz, Solitude and Leadership

"Wide is the range of words, one one side and the other."
   - Homer

"Hell is truth seen too late"
   - Thomas Hobbes

"To shun the heaven that leads men to this hell"
   - Shakespeare, Sonnet 129


* tmp
Ma Xiaowei, China’s health commission minister, also revealed on Sunday that
the incubation period was between one and 14 days, and that the virus was
infectious during its incubation period when people may show no symptoms.
   - [[https://www.ft.com/content/7bb597c8-3ff7-11ea-a047-eae9bd51ceba][ft]]

“That’s why you never really hear about problems emerging on a local scale in
 China,” said John Yasuda, who studies China’s approach to health crises at
 Indiana University. “By the time that we hear about it, and that the problem
 reaches the central government, it’s because it’s become a huge problem.”
   - [[https://nyti.ms/38FTXIO][NYT]]
