# Quotes

* Freedom
"A pawn acts like a pawn because it believes its a pawn"
   - An Old Man playing chess, Wu-Tang: An American Saga

"If one minute’s freedom had been offered to me, and I had been told must die at
 the end of that minute, I would have taken it."
   - Mum Bett

"There are only three real sports: bullfighting, mountain climbing, and motor
racing. The rest are merely games."
   - Ernest Hemingway


* Death
"Another repied to his confessor, who was promising him that he should sup that
 day with Our Lord: You go there yourself; for my part, I'm fasting."
  - Michel de Montaigne, That the Taste of Good and Evil Depends in Large Part
                         on the Opinion We Have of Them

"Death holds less pain than does the wait for death"
  - Ovid


* Happiness
"For people are happy not in hilarity or sensuality or laughter, nor in games,
 the comrades of levity, but often even in sadness through firmness and
 constancy"
 - Cicero

"Happiness is reality minus expectations"


* Humor
"Why don't you take your library card and fuck off."
  - Logan Roy, Succession 2:4

"Even on the highest throne in the world, we are still sitting on our ass."
  - Michel de Montaigne

"Difficulty is a coin which the learned conjure with so as not to reveal the
 vanity of their studies and which human stupidity is keen to accept as payment"
  - Michel de Montaigne

"But with the invention of the modern prison system, everything happened in
 private, behind locked gates. One could no longer see and therefore resist
 state power."
  - Based on Foucault's Discipline and Punish

"The most difficult thing in the world is to know how to do a thing and to watch
 someone else do it wrong without comment."
  - Theodore H. White


* Thoughts
"And if I am a man of some reading, I am a man of no retentiveness"
  - Michel de Montaigne

"Hypocrisy is the homage vice pays to virtue."

"So marvelous is the power of conscience! It makes us betray, accuse and fight
 ourselves, and, in the absence of an outside witness, it brings us forward
 against ourselves."
       `Plying a secret whip, our soul as torturer.` - Juvenal
  - Michel de Montaigne

"Spirit of iron makes skin of stone."
  - Ta-Nehisi Coates, Black Panther

"Wide is the range of words, one one side and the other."
  - Homer

"Hell is truth seen too late"
  - Thomas Hobbes

"To shun the heaven that leads men to this hell"
  - Shakespeare, Sonnet 129


* Politics
"In politics, identity is an appeal to authority—the moral authority of the
oppressed: I am what I am, which explains my view and makes it the truth. The
politics of identity starts out with the universal principles of equality,
dignity, and freedom, but in practice it becomes an end in itself—often a dead
end, a trap from which there’s no easy escape and maybe no desire for escape"
  - George Packer, [[https://www.theatlantic.com/magazine/archive/2019/10/when-the-culture-war-comes-for-the-kids/596668/][When the Culture War Comes for the Kids]]
